spring.application.name=01_Insurance_Policy_and_Claim_Management_System

spring.datasource.url=jdbc:mysql://localhost:3306/insurance_policy_claim_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsASecretKeyForInsuranceProjectJwtAuthentication
jwt.expiration=60000000

logging.level.root=INFO
logging.level.com.monocept.demo=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Cloudinary settings
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# Email otp setting

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=universalidprashant88@gmail.com
spring.mail.password=ihif lnxt ibhi xpbf


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=${TWILIO_ACC_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${PHONE_NO}